import Quotes from "../components/quotes";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Box_Title}>
        <h1>POKEDEX</h1>
        <Link href="/pokedex">
          <img className={styles.Pokedex__Img} src="/pokedex.png" />
        </Link>
      </div>
      <p className={styles.Box_Para}>
        Here's your Pokédex, <br /> <br /> click on it
      </p>
      <Quotes
        paragraph="«I see now that the circumstances of one's birth are irrelevant. It is what you do with the gift of life that determines who you are.»"
        title="Mewtwo"
        imageSrc="https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png"
      />
      <Quotes
        paragraph="«Take charge of your destiny»"
        title="Rayquaza"
        imageSrc="https://media.pokemoncentral.it/wiki/thumb/1/16/Artwork0384_ROZA.png/200px-Artwork0384_ROZA.png"
      />
    </>
  );
}
